name: testing-server

services:
  postgres:
    image: postgres
    container_name: testing-server-postgres
    environment:
      POSTGRES_DB: testing-server-2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - testing-server_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  testing-server_postgres_data: